version: 2.1

orbs:
  cloudsmith: cloudsmith/cloudsmith@1.0.5
  sign-packages: opennms/sign-packages@2.3.0

parameters:
  debian-version:
    type: string
    default: stretch
  maven-version:
    type: string
    default: 3.6.3
  # 11.5.0 is the last version with JDK8 installed
  xcode-version:
    type: string
    default: 11.5.0

executors:
  centos-sign-executor:
    docker:
      - image: opennms/build-env:1.8.0.302.b08-3.6.3-b8090
  debian-sign-executor:
    docker:
      - image: opennms/build-env:debian-jdk8-b8242
  centos-x86-executor:
    docker:
      - image: i386/centos:7
  centos-x64-executor:
    docker:
      - image: centos:7
  debian-x86-executor:
    docker:
      - image: i386/debian:<< pipeline.parameters.debian-version >>
  debian-x64-executor:
    docker:
      - image: debian:<< pipeline.parameters.debian-version >>

commands:
  fetch-maven:
    description: Fetch Maven
    parameters:
      maven-version:
        type: string
        default: << pipeline.parameters.maven-version >>
    steps:
      - restore_cache:
          keys:
            - maven-{{ .Branch }}-{{ .Revision }}
            - maven-{{ .Branch }}-
            - maven-
      - run:
          name: download and unpack Maven
          command: |
            if [ ! -x ~/maven/bin/mvn ]; then
              mkdir -p ~/maven
              export MAVEN_TARBALL="https://downloads.apache.org/maven/maven-3/<< parameters.maven-version >>/binaries/apache-maven-<< parameters.maven-version >>-bin.tar.gz"
              ( curl -L -o - "$MAVEN_TARBALL" || wget -O - "$MAVEN_TARBALL" ) | \
                tar --strip-components=1 -C ~/maven -xvzf -
            fi
      - save_cache:
          key: maven-{{ .Branch }}-{{ .Revision }}
          paths:
            - maven

  fetch-rpm-dependencies:
    description: Fetch RPM Dependencies
    parameters:
      type:
        type: string
    steps:
      - cache-restore:
          key: rpm-<< parameters.type >>
          path: /var/cache/yum
      - run:
          name: download packages from yum
          command: yum -y --downloadonly install automake autoconf curl gcc git gnupg2 java-1.8.0-openjdk-devel libtool make rpm-build which
      - cache-save:
          key: rpm-<< parameters.type >>
          path: /var/cache/yum
      - run:
          name: install packages
          command: yum -y install automake autoconf curl gcc git gnupg2 java-1.8.0-openjdk-devel libtool make rpm-build which

  fetch-debian-dependencies:
    description: Fetch Debian Dependencies
    parameters:
      type:
        type: string
    steps:
      - run:
          name: install prerequisites
          command: |
            # this makes it easier to use in circleci or root images without changing things
            SUDO="$(command -v sudo || :)"
            if [ ! -x "$SUDO" ]; then
              apt -q update
              apt -y -q --allow-unauthenticated install sudo
            fi

            sudo apt -q update
            sudo apt -y -q install gnupg2 software-properties-common

            echo "deb http://deb.debian.org/debian << pipeline.parameters.debian-version >>-backports main" | sudo tee /etc/apt/sources.list.d/<< pipeline.parameters.debian-version >>-backports.list
            echo "deb http://deb.debian.org/debian-security << pipeline.parameters.debian-version >>/updates main" | sudo tee /etc/apt/sources.list.d/<< pipeline.parameters.debian-version >>-security.list
            sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 04EE7237B7D453EC 648ACFD622F3D138 0E98404D386FA1D9 AA8E81B4331F7F50 112695A0E562B32A
            sudo apt -q update
            sudo apt -y -q -t << pipeline.parameters.debian-version >>-backports install apt-transport-https ca-certificates
      - cache-restore:
          key: debian-<< parameters.type >>
          path: /var/cache/apt
      - run:
          name: download jdk
          command: sudo apt -y --download-only -q -t << pipeline.parameters.debian-version >>-backports install openjdk-8-jdk-headless
      - run:
          name: download other dependencies
          command: sudo apt -y --download-only -q install autotools-dev autoconf automake cdbs curl debhelper debianutils devscripts dpkg-dev git software-properties-common
      - cache-save:
          key: debian-<< parameters.type >>
          path: /var/cache/apt
      - run:
          name: install jdk
          command: sudo apt -y -q -t << pipeline.parameters.debian-version >>-backports install openjdk-8-jdk-headless
      - run:
          name: install other dependencies
          command: sudo apt -y -q install autotools-dev autoconf automake cdbs curl debhelper debianutils devscripts dpkg-dev git software-properties-common

  clean-caches:
    steps:
      - run:
          name: Clean Old Cache Objects
          command: |
            mkdir -p ~/.m2/repository ~/.npm
            find ~/.m2/repository ~/.npm -depth -ctime "+7" -type f -exec rm {} \; >/dev/null
            find ~/.m2/repository ~/.npm -depth -type d -print | while read -r DIR; do
              rmdir "$DIR" 2>/dev/null || :
            done

  cache-restore:
    parameters:
      key:
        description: the unique id for this cache
        type: string
      path:
        description: the path to restore to
        type: string
    description: "Restore Cache: << parameters.key >>"
    steps:
      - restore_cache:
          keys:
            - cache-<< parameters.key >>-{{ .Branch }}-{{ .Revision }}
            - cache-<< parameters.key >>-{{ .Branch }}
            - cache-<< parameters.key >>-
      - run:
          name: "extract tarball to << parameters.path >>"
          command: |
            if [ -e "/tmp/cache-<< parameters.key >>.tar.gz" ]; then
              mkdir -p "<< parameters.path >>"
              if [ "$UID" -eq 0 ]; then
                tar -C "<< parameters.path >>" -xvf "/tmp/cache-<< parameters.key >>.tar.gz"
              else
                sudo tar -C "<< parameters.path >>" -xvf "/tmp/cache-<< parameters.key >>.tar.gz"
                sudo chown -R "$UID" "<< parameters.path >>"
              fi
            fi

  cache-save:
    parameters:
      key:
        description: the unique id for this cache
        type: string
      path:
        description: the path to cache
        type: string
    description: "Save Cache: << parameters.key >>"
    steps:
      - run:
          name: "create a tarball from << parameters.path >>"
          command: |
            if [ -d "<< parameters.path >>" ]; then
              SAVEDIR="<< parameters.path >>"
              CACHE_TARBALL="/tmp/cache-<< parameters.key >>.tar.gz"

              if [ "$UID" -eq 0 ]; then
                rm -f "${CACHE_TARBALL}" || :
                tar -C "${SAVEDIR}" -cvf "${CACHE_TARBALL}" .
                chmod a+rw "${CACHE_TARBALL}"
              else
                sudo rm -f "${CACHE_TARBALL}" || :
                sudo tar -C "${SAVEDIR}" -cvf "${CACHE_TARBALL}" .
                sudo chmod a+rw "${CACHE_TARBALL}"
                sudo chown "$UID" "${CACHE_TARBALL}"
              fi
            fi
      - save_cache:
          key: cache-<< parameters.key >>-{{ .Branch }}-{{ .Revision }}
          paths:
            - "/tmp/cache-<< parameters.key >>.tar.gz"

  do-build:
    description: Compile JICMP
    parameters:
      arch:
        type: string
      platform:
        type: string
    steps:
      - clean-caches
      - run:
          name: configure and build
          command: |
            export PATH="$HOME/maven/bin:$PATH"
            ./configure
            make
            make install DESTDIR="$(pwd -P)/target"
      - run:
          name: save artifacts
          when: always
          command: |
            mkdir -p ~/"artifacts/<< parameters.platform >>/<< parameters.arch >>/"
            cp config.log config.status ~/"artifacts/<< parameters.platform >>/<< parameters.arch >>/"
            mv target/usr/local/lib/*jicmp* ~/"artifacts/<< parameters.platform >>/<< parameters.arch >>/"
      - store_artifacts:
          path: ~/artifacts/<< parameters.platform >>/<< parameters.arch >>/
          destination: << parameters.platform >>-<< parameters.arch >>

jobs:
  build-source:
    executor: centos-x64-executor
    steps:
      - fetch-rpm-dependencies:
          type: x64
      - fetch-maven
      - checkout
      - cache-restore:
          key: maven
          path: $HOME/.m2
      - clean-caches
      - run:
          name: autoconf, configure, make arch-independent
          command: |
            git submodule init && git submodule update
            autoreconf -fvi
            ./configure
            make dist
            ~/maven/bin/mvn install
            mkdir -p ~/artifacts/{source,java}
            mv jicmp-*.tar.gz ~/artifacts/source/
            mv target/*.jar ~/artifacts/java/
            make clean
      - cache-save:
          key: maven
          path: $HOME/.m2
      - store_artifacts:
          path: ~/artifacts/java/
          destination: java
      - store_artifacts:
          path: ~/artifacts/source/
          destination: source
      - persist_to_workspace:
          root: ~/
          paths:
            - project
            - artifacts

  build-mac:
    macos:
      xcode: << pipeline.parameters.xcode-version >>
    steps:
      - fetch-maven
      - checkout
      - attach_workspace:
          at: ~/
      - do-build:
          arch: x86_64
          platform: macosx

  build-centos-x86:
    executor: centos-x86-executor
    steps:
      - fetch-rpm-dependencies:
          type: x86
      - fetch-maven
      - checkout
      - attach_workspace:
          at: ~/
      - do-build:
          arch: i386
          platform: linux
      - run:
          name: build x86 RPM
          command: |
            mkdir -p target/rpm/{SOURCES,BUILD}
            cp ~/artifacts/source/jicmp-*.tar.gz target/rpm/SOURCES/
            rpmbuild --define "_topdir $(pwd -P)/target/rpm" --define "rel 0.${CIRCLE_BUILD_NUM}" --target=i686 -ba jicmp.spec
            mkdir -p ~/artifacts/packages/rpm/i386/
            mv target/rpm/RPMS/*/*.rpm ~/artifacts/packages/rpm/i386/
      - persist_to_workspace:
          root: ~/
          paths:
            - artifacts/packages/rpm/i386/

  build-centos-x64:
    executor: centos-x64-executor
    steps:
      - fetch-rpm-dependencies:
          type: x64
      - fetch-maven
      - checkout
      - attach_workspace:
          at: ~/
      - do-build:
          arch: x86_64
          platform: linux
      - run:
          name: build x64 RPM
          command: |
            mkdir -p target/rpm/{SOURCES,BUILD}
            cp ~/artifacts/source/jicmp-*.tar.gz target/rpm/SOURCES/
            rpmbuild --define "_topdir $(pwd -P)/target/rpm" --define "rel 0.${CIRCLE_BUILD_NUM}" --target=x86_64 -ba jicmp.spec
            mkdir -p ~/artifacts/packages/rpm/{source,x86_64}/
            mv target/rpm/SRPMS/*.rpm ~/artifacts/packages/rpm/source/
            mv target/rpm/RPMS/*/*.rpm ~/artifacts/packages/rpm/x86_64/
      - persist_to_workspace:
          root: ~/
          paths:
            - artifacts/packages/rpm/source/
            - artifacts/packages/rpm/x86_64/
      - store_artifacts:
          path: ~/artifacts/packages/rpm/source/
          destination: rpm

  build-debian-x86:
    executor: debian-x86-executor
    steps:
      - fetch-debian-dependencies:
          type: x86
      - fetch-maven
      - checkout
      - attach_workspace:
          at: ~/
      - do-build:
          arch: i386
          platform: linux
      - run:
          name: build x86 Debian packages
          command: |
            git submodule init && git submodule update
            autoreconf -fvi
            VERSION="$(./configure --version | grep 'jicmp configure' | cut -d' ' -f3)"
            export DEB_TAR_SRCDIR="jicmp-${VERSION}"
            dch --controlmaint --newversion="${VERSION}-0.${CIRCLE_BUILD_NUM}" --urgency=low --distribution='UNRELEASED' "Automated build from CircleCI: https://github.com/OpenNMS/jicmp/commit/${CIRCLE_SHA}"
            dpkg-buildpackage
            mkdir -p ~/artifacts/packages/debian/i386/
            mv ../jicmp_* ~/artifacts/packages/debian/i386/
      - persist_to_workspace:
          root: ~/
          paths:
            - artifacts/packages/debian/i386/

  build-debian-x64:
    executor: debian-x64-executor
    steps:
      - fetch-debian-dependencies:
          type: x64
      - fetch-maven
      - checkout
      - attach_workspace:
          at: ~/
      - do-build:
          arch: x86_64
          platform: linux
      - run:
          name: build x64 Debian packages
          command: |
            git submodule init && git submodule update
            autoreconf -fvi
            VERSION="$(./configure --version | grep 'jicmp configure' | cut -d' ' -f3)"
            export DEB_TAR_SRCDIR="jicmp-${VERSION}"
            dch --controlmaint --newversion="${VERSION}-0.${CIRCLE_BUILD_NUM}" --urgency=low --distribution='UNRELEASED' "Automated build from CircleCI: https://github.com/OpenNMS/jicmp/commit/${CIRCLE_SHA}"
            dpkg-buildpackage
            mkdir -p ~/artifacts/packages/debian/x86_64/
            mv ../jicmp_* ~/artifacts/packages/debian/x86_64/
      - persist_to_workspace:
          root: ~/
          paths:
            - artifacts/packages/debian/x86_64/

  sign-rpms:
    executor: centos-sign-executor
    steps:
      - attach_workspace:
          at: ~/
      - sign-packages/install-rpm-dependencies
      - sign-packages/setup-env:
          gnupg_home: ~/tmp/gpg
      - sign-packages/sign-rpms:
          gnupg_home: ~/tmp/gpg
          gnupg_key: opennms@opennms.org
          packages: ~/artifacts/packages/rpm/*/*.rpm
      - run:
          name: prepare artifacts
          command: |
            mkdir -p ~/artifacts/packages/rpm-signed/
            cp -f ~/artifacts/packages/rpm/{i386,x86_64}/*.rpm ~/artifacts/packages/rpm-signed/
      - store_artifacts:
          path: ~/artifacts/packages/rpm-signed/
          destination: rpm
      - persist_to_workspace:
          root: ~/
          paths:
            - artifacts/packages/rpm-signed/

  sign-debs:
    executor: debian-sign-executor
    steps:
      - attach_workspace:
          at: ~/
      - sign-packages/install-deb-dependencies
      - sign-packages/setup-env:
          gnupg_home: ~/tmp/gpg
      - sign-packages/sign-debs:
          gnupg_home: ~/tmp/gpg
          gnupg_key: opennms@opennms.org
          packages: ~/artifacts/packages/debian/*/*.deb
      - run:
          name: prepare artifacts
          command: |
            mkdir -p ~/artifacts/packages/debian-signed/
            cp -f ~/artifacts/packages/debian/i386/* ~/artifacts/packages/debian-signed/
            cp -f ~/artifacts/packages/debian/x86_64/* ~/artifacts/packages/debian-signed/
      - store_artifacts:
          path: ~/artifacts/packages/debian-signed/
          destination: debian
      - persist_to_workspace:
          root: ~/
          paths:
            - artifacts/packages/debian-signed/

  publish:
    executor: cloudsmith/default
    steps:
      - attach_workspace:
          at: ~/
      - cloudsmith/ensure-api-key
      - cloudsmith/install-cli
      - cloudsmith/publish:
          allow-republish: true
          cloudsmith-repository: opennms/common-testing
          package-format: rpm
          package-distribution: el/7
          package-path: ~/artifacts/packages/rpm-signed/jicmp-2*.i686.rpm
      - cloudsmith/publish:
          allow-republish: true
          cloudsmith-repository: opennms/common-testing
          package-format: rpm
          package-distribution: el/7
          package-path: ~/artifacts/packages/rpm-signed/jicmp-debuginfo-2*.i686.rpm
      - cloudsmith/publish:
          allow-republish: true
          cloudsmith-repository: opennms/common-testing
          package-format: rpm
          package-distribution: el/7
          package-path: ~/artifacts/packages/rpm-signed/jicmp-2*.x86_64.rpm
      - cloudsmith/publish:
          allow-republish: true
          cloudsmith-repository: opennms/common-testing
          package-format: rpm
          package-distribution: el/7
          package-path: ~/artifacts/packages/rpm-signed/jicmp-debuginfo-2*.x86_64.rpm
      - cloudsmith/publish:
          allow-republish: true
          cloudsmith-repository: opennms/common-testing
          package-format: rpm
          package-distribution: el/8
          package-path: ~/artifacts/packages/rpm-signed/jicmp-2*.x86_64.rpm
      - cloudsmith/publish:
          allow-republish: true
          cloudsmith-repository: opennms/common-testing
          package-format: rpm
          package-distribution: el/8
          package-path: ~/artifacts/packages/rpm-signed/jicmp-debuginfo-2*.x86_64.rpm
      - cloudsmith/publish:
          allow-republish: true
          cloudsmith-repository: opennms/common-testing
          package-format: deb
          package-distribution: any-distro/any-version
          package-path: ~/artifacts/packages/debian-signed/jicmp_*_i386.deb
      - cloudsmith/publish:
          allow-republish: true
          cloudsmith-repository: opennms/common-testing
          package-format: deb
          package-distribution: any-distro/any-version
          package-path: ~/artifacts/packages/debian-signed/jicmp_*_amd64.deb

  build-docs:
    docker:
      - image: cimg/openjdk:8.0-node
    steps:
      - checkout
      - fetch-maven
      - attach_workspace:
          at: ~/
      - fetch-debian-dependencies:
          type: docs
      - cache-restore:
          key: maven
          path: $HOME/.m2
      - cache-restore:
          key: node
          path: $HOME/.npm
      - clean-caches
      - run:
          name: Build Documentation
          command: |
            make clean
            ./configure
            make docs
            mkdir -p ~/artifacts
            mv target/*-javadoc.jar ~/artifacts/
            mv build/site.zip ~/artifacts/
      - cache-save:
          key: node
          path: $HOME/.npm
      - cache-save:
          key: maven
          path: $HOME/.m2
      - store_artifacts:
          path: ~/artifacts/
          destination: /
      - persist_to_workspace:
          root: ~/
          paths:
            - artifacts

workflows:
  version: 2.1

  build-workflow:
    jobs:
      - build-source
      - build-docs:
          requires:
            - build-source
      - build-debian-x86:
          requires:
            - build-source
      - build-debian-x64:
          requires:
            - build-source
      - build-centos-x86:
          requires:
            - build-source
      - build-centos-x64:
          requires:
            - build-source
      - build-mac:
          requires:
            - build-source
      - sign-debs:
          requires:
            - build-debian-x86
            - build-debian-x64
      - sign-rpms:
          requires:
            - build-centos-x86
            - build-centos-x64
      - publish:
          filters:
            branches:
              only:
                - master
          requires:
            - sign-debs
            - sign-rpms
